### ISSUE TITLE
Tip: some python scripts to help you export all your forms, pages, sections & css from DB to flat files

### ISSUE THREAD

**Issue by maniqui** [gocom/rah_flat#15]
Hi all. 
In case you have many forms in your existing Textpattern website and you are moving into flat file templates, here is a quick script to export all your forms from your database into flat files. This way, you avoid the "newfile-copy-paste-save-givename" dance :)

I've tested it in Linux. It will probably work on Mac and Windows too.

How to use it? 
1. open a command line. 
2. create and/or navigate to some empty folder (it could be your `templates/forms` folder)
3. run the python console (usually, you just have to type `python`).
4. run the following script.
5. profit!

``` python
import MySQLdb

db = MySQLdb.connect(host="", user="", passwd="", db="") # fill in with your database details
cursor = db.cursor()
sql = """SELECT * FROM txp_form"""
cursor.execute(sql)
forms = cursor.fetchall()
for form in forms:
    file = open(form[0]+'.'+form[1]+'.txp', "w")
    print>>file, form[2]
    file.close()
db.close()
```

The script is easily adaptable to export pages. And probably easy to export styles too. It won't work as is for sections or preferences, as it would require to transform the data into JSON format.

Edit: see below for scripts to export Pages, Styles, and Sections.

**Comment by maniqui** [comment]
This is the version for exporting styles into flat CSS files.

```
import MySQLdb

db = MySQLdb.connect(host="", user="csf", passwd="d35try", db="csf") # fill in with your database details
cursor = db.cursor()
sql = """SELECT * FROM txp_css"""
cursor.execute(sql)
styles = cursor.fetchall()
for css in styles:
    file = open(css[0]+'.css', "w")
    print>>file, css[1]
    file.close()
db.close()
```

**Comment by maniqui** [comment]
And finally, here is the Python script that will let you export Sections to flat files:

```python
import MySQLdb
import json
import collections

db = MySQLdb.connect(host="", user="csf", passwd="d35try", db="csf") # fill in with your database details
cursor = db.cursor()
sql = """SELECT * FROM txp_section"""
cursor.execute(sql)
sections = cursor.fetchall()
for section in sections:
    file = open(section[0]+'.json', "w")
    d = collections.OrderedDict()
    d['name'] = section[0]
    d['title'] = section[6]
    d['page'] = section[1]
    d['css'] = section[2]
    d['in_rss'] = bool(section[3])
    d['on_frontpage'] = bool(section[4])
    d['searchable'] = bool(section[5])

    j = json.dumps(d, indent=4)
    print>>file, j
    file.close()
db.close()
```

**Comment by maniqui** [comment]
And here is the Python script that will let you export pages to flat files:

```python
import MySQLdb
db = MySQLdb.connect(host="", user="", passwd="", db="") # fill in with your database details
cursor = db.cursor()
sql = """SELECT * FROM txp_page"""
cursor.execute(sql)
pages = cursor.fetchall()
for page in pages:
    file = open(page[0]+'.txp', "w")
    print>>file, page[1]
    file.close()
db.close()
```

**Comment by Manaus** [comment]
Hi, since the mysqldb module is returning odd errors on my mac, I'm wondering if I can use a template manager like cnk_versioning or cxc_templates to do the gross work (pages, forms, css) and fine-tune by hand...

**Comment by c2mrdale** [comment]
I use mem_templates alongside rah_flat to export templates.
