### ISSUE TITLE
Prefs: option to set label and form input type?

### ISSUE THREAD

**Issue by jools-r** [gocom/rah_flat#25]
It would be really useful to be able to specify:

* the form input type for admin-editable prefs
* the Pref label name (instead of rah_flat_variable_custom_pref_name)

e.g. in a prefs.json file.

**Comment by NicolasGraph** [comment]
@jools-r, you should already be able to change the pref label via a Textpack.

**Comment by NicolasGraph** [comment]
I would also like to see a way to define the variables widgets.
It could be done as it was previously for prefs (via a `.json` file), or via the variable filename like forms with their types (`example.yesnoradio.txt`), with a fallback to `text_input`.
